# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change working directory
      run: cd src
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
                     2.0.x
                     2.1.x
                     3.1.x
                     5.0.x
                     6.0.x
                     7.0.x
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - name: Build
      run: dotnet build
      working-directory: src
    - name: Pack
      run: dotnet pack
      working-directory: src
    - name: Upload Artifact EleCho.GoCqHttpSdk
      uses: actions/upload-artifact@v3
      with:
        name: EleCho.GoCqHttpSdk
        path: src/EleCho.GoCqHttpSdk/bin/Debug/*.nupkg
    - name: Upload Artifact EleCho.GoCqHttpSdk.CommandExecuting
      uses: actions/upload-artifact@v3
      with:
        name: EleCho.GoCqHttpSdk.CommandExecuting
        path: src/EleCho.GoCqHttpSdk.CommandExecuting/bin/Debug/*.nupkg
    - name: Upload Artifact EleCho.GoCqHttpSdk.MessageMatching
      uses: actions/upload-artifact@v3
      with:
        name: EleCho.GoCqHttpSdk.MessageMatching
        path: src/EleCho.GoCqHttpSdk.MessageMatching/bin/Debug/*.nupkg
        
  Release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download EleCho.GoCqHttpSdk
      uses: actions/download-artifact@v3
      with:
       name: EleCho.GoCqHttpSdk
    
    - name: Download EleCho.GoCqHttpSdk.CommandExecuting
      uses: actions/download-artifact@v3
      with:
       name: EleCho.GoCqHttpSdk.CommandExecuting
    - name: Download EleCho.GoCqHttpSdk.MessageMatching
      uses: actions/download-artifact@v3
      with:
       name: EleCho.GoCqHttpSdk.MessageMatching

    - name: Create Release
      if: github.event_name != 'pull_request' 
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: AutoBuild
        title: "自动构建版本"
        files: |
              *.nupkg
 
